apiVersion: v1
kind: Namespace
metadata:
  name: vci-flux-secret-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcluster-platform-flux-secret-controller
  namespace: vci-flux-secret-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vcluster-platform-flux-secret-controller
rules:
  - apiGroups: ["management.loft.sh"]
    resources: ["virtualclusterinstances", "virtualclusterinstances/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.loft.sh"]
    resources: ["accesskeys"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vcluster-platform-flux-secret-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vcluster-platform-flux-secret-controller
subjects:
  - kind: ServiceAccount
    name: vcluster-platform-flux-secret-controller
    namespace: vci-flux-secret-controller
